Internationalization
camellia-app/camellia pull request #151
Opened 2022-06-26 16:22 UTC by flaksp

2022-07-01 05:04 UTC, tischenkob commented
dept -> debt

2022-07-01 05:22 UTC, tischenkob requested changes
Ваш ПР полный отстой. Переделывайте

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "View all your browser bookmarks at the new tab screen.",
_on_ the new tab

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "We're using Sentry to track errors in Camellia. At this moment there's no way to disable this option.",
We use

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "We're gathering anonymous usage statistics via Google Analytics. We need such data to be sure our updates make Camellia better. We don't track links you visit, we don't analyze your b
We gather
Boormarks _or_ folder~~s~~ names

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "By default, Camellia displays photographer's name in bottom toolbar, which can be clicked to open full photo if you wish to save it or explore more photos of the author. The attributi
in _the_ bottom toolbar
open _the_ full photo
photos of the author -> works of the author, чтобы не повторяться

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "Show \"Search\" button"
Здесь и дальше артикль the перед заголовком кнопки. Дальше еще the перед bottom toolbar

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "Information that may be helpful for debugging purposes will be copied to your clipboard by pressing the button. You are safe to share this information with community of contributors v
Тут лучше can be copied, потому что кнопку можно и не нажать никогда. the button -> this button?

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "Should content be centered or not. Centering content may be useful for people with wide displays."
Centers the content. It may be useful for people with wide_r_ displays

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "message": "Link pointing to Unsplash collection in form of \"$URL$\".",
in _the_ form of

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "description": "Label of the close button in bookmark search text field. This text shown when hovering the button."
in _the_ bookmark search field. _It_ _is_ shown

2022-07-01 05:22 UTC, tischenkob commented on translations/en/messages.json
> +    "description": "Label of the bookmark category that contains bookmarks from 'Bookmarks bar' folder."
Здесь и дальше артикль the перед названиями папок и тулбаров

2022-07-04 13:29 UTC, flaksp commented on src/api/i18n/translate.ts
> +  switch (getPlatform()) {
Когда-нибудь потом отрефакторим

2022-07-05 06:07 UTC, tischenkob approved these changes
Мда

2022-07-05 06:35 UTC, merged